apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blast

bases:
- matchbox-configmap/groups
- matchbox-configmap/ignition
- matchbox-configmap/profiles

resources: 
- ns.yaml 
- matchbox-rpc-secret.yaml
- matchbox-deployment.yaml
- matchbox-service.yaml
- matchbox-ingress.yaml
- dnsmasq.yaml
