apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Needed for configmapgenerator to work properly
namespace: blast

bases:
- groups/
- ignition/
- profiles/

configMapGenerator:
  - name: custom-dnsmasq
    files:
    - dnsmasq/02-custom.conf
    - dnsmasq/addn-hosts
