apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Avoiding the use of kustomize namespace, due to
# helmcharts HAVING to be deployed in kube-system

resources: 
- ns.yaml
- pihole.yaml
- service.yaml
