apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources: 
- ns.yaml
- deployment.yaml
# TODO - move secret to SealedSecret (this is a gernic password for now)
- secret.yaml
- service.yaml
- service-external.yaml
