ssh_authorized_keys:
  - github:ssmiller25
hostname: {{.hostname}}
k3os:
  modules:
  - kvm
  dns_nameservers:
  - 8.8.8.8
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  k3s_args:
  - agent
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: true
